### ISSUE TITLE
URLError: <urlopen error [Errno 13] Permission denied>

### ISSUE THREAD

**Issue by geojacobm6** [mback2k/django-appengine-auth#1]
Hi, I am getting this error due to using urlopen in django-socail_auth package.

How can i solve, this?

> Internal Server Error: /complete/google-appengine-oauth2/
> Traceback (most recent call last):
>   File "/base/data/home/apps/s~te-707/2.390352587636734850/django/core/handlers/base.py", line 113, in get_response
>     response = callback(request, _callback_args, *_callback_kwargs)
>   File "/base/data/home/apps/s~te-707/2.390352587636734850/django/views/decorators/csrf.py", line 77, in wrapped_view
>     return view_func(_args, *_kwargs)
>   File "lib/social_auth/decorators.py", line 29, in wrapper
>     return func(request, request.social_auth_backend, _args, *_kwargs)
>   File "lib/social_auth/views.py", line 41, in complete
>     return complete_process(request, backend, _args, *_kwargs)
>   File "lib/social_auth/views.py", line 107, in complete_process
>     user = auth_complete(request, backend, _args, *_kwargs)
>   File "lib/social_auth/views.py", line 190, in auth_complete
>     return backend.auth_complete(user=user, request=request, _args, *_kwargs)
>   File "lib/social_auth/backends/**init**.py", line 853, in auth_complete
>     response = simplejson.loads(dsa_urlopen(request).read())
>   File "lib/social_auth/utils.py", line 237, in dsa_urlopen
>     return urlopen(_args, *_kwargs)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 127, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 422, in _open
>     '_open', req)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 1222, in https_open
>     return self.do_open(httplib.HTTPSConnection, req)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 1184, in do_open
>     raise URLError(err)
> URLError: <urlopen error [Errno 13] Permission denied>

**Comment by mback2k** [comment]
Hi, sorry, I don't see anything related to appengine_auth in the stacktrace. Are you sure this error is caused by the appengine_auth package?

**Comment by mback2k** [comment]
And you probably want to use https://github.com/mback2k/python-appengine-auth for https://github.com/omab/python-social-auth instead of this legacy package for django-social-auth.
